services:
  
  etl-app:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./data:${DATA_DIR}
      - ./logs:${LOG_DIR}
    env_file:
      - .env
    networks:
      - etl-network
    
  mongo:
    command: 
      - mongod
      - --quiet
      - --setParameter
      - logLevel=0
      - --logpath
      - /app/logs/mongodb.log
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}    
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_ANALYST_USERNAME=${MONGO_ANALYST_USER}    
      - MONGO_INITDB_ANALYST_PASSWORD=${MONGO_ANALYST_PASSWORD}
      - DATA_DIR=${DATA_DIR}
      - LOG_DIR=${LOG_DIR}
    volumes:
      - mongo_data:${DATA_DIR}
      - ./logs:${LOG_DIR}
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - etl-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]  
      interval: 20s
      timeout: 10s
      retries: 3      

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      # --- CONNEXION ADMIN (PAR DÉFAUT) ---
      # Permet de voir toutes les bases de données et de tout gérer.
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}      
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}  
      
      # --- CONNEXION ANALYSTE (ALTERNATIVE) ---
      # Pour tester les droits de lecture seule, commentez les 3 lignes ci-dessus
      # et décommentez les 4 lignes ci-dessous.   
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      # - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGO_DATABASE}
      # - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ANALYST_USER}
      # - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ANALYST_PASSWORD}
      
      - ME_CONFIG_BASICAUTH_USERNAME=${WEB_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${WEB_PASSWORD}
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_SITE_BASEURL=/
      - ME_CONFIG_SITE_COOKIESECRET=somesecretkey
      - ME_CONFIG_SITE_SESSIONSECRET=anothersecretkey

    depends_on:
      etl-app:
        condition: service_completed_successfully
    networks:
      - etl-network

networks:
  etl-network:
    driver: bridge
volumes:
  mongo_data: